import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import getStream from "get-stream";
import { PassThrough } from "stream";

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();
    const {
      name,
      fullName,
      email = "No Email",
      experience = "None",
      skills = "None",
    } = data;
    const resolvedName = name || fullName || "No Name";

    console.log("📥 Resume Input:", { name: resolvedName, email, experience, skills });

    const doc = new PDFDocument();
    const stream = new PassThrough();
    doc.pipe(stream);

    doc.fontSize(20).text("Resume", { align: "center" }).moveDown();
    doc.fontSize(14).text(`Name: ${resolvedName}`);
    doc.text(`Email: ${email}`);
    doc.moveDown().fontSize(12).text("Experience:");
    doc.text(experience);
    doc.moveDown().text("Skills:");
    doc.text(skills);
    doc.moveDown().text("Generated by ShiftAI");
    doc.end();

    const buffer = await getStream.buffer(stream);
    console.log("📦 PDF Buffer Size:", buffer.length);

    return new NextResponse(buffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${resolvedName}_resume.pdf"`,
      },
    });
  } catch (error) {
    console.error("❌ PDF Error:", error);
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 });
  }
}
